const OK = 200;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const UNIQUE_EMAIL = 409;
const DEFAULT = 500;
const CREATED = 201;

module.exports = {
  OK,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  UNIQUE_EMAIL,
  DEFAULT,
  CREATED,
};
